# This file was generated by GoReleaser. DO NOT EDIT.
cask "convoy" do
  version "0.27.0"

  on_macos do
    on_intel do
      sha256 "82ec2ce555c52b426ce35671f51414199b2f38f4c8535b74ef6f9a3bf8de1453"
      url "https://github.com/endeavordata/homebrew-tap/releases/download/v#{version}/convoy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc17714ce1c2b6a54bf6dd25ce971f290d4b89db0fbe8423d2ce4cb6e1c6970d"
      url "https://github.com/endeavordata/homebrew-tap/releases/download/v#{version}/convoy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "convoy"
  desc "Convoy — Endeavor Labs internal PSA CLI"
  homepage "https://github.com/endeavordata/convoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "convoy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/convoy"]
    end
  end

  # No zap stanza required

end
