# This file was generated by GoReleaser. DO NOT EDIT.
cask "convoy" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "d207a88eee81f596aeb42c7e66d68ec1fcb56aa41eb66b95698b969732e7d564"
      url "https://github.com/endeavordata/homebrew-tap/releases/download/v#{version}/convoy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4f51848b06d7a5e485a8d20c188aa004944e18fe265ef479666ad63be124647"
      url "https://github.com/endeavordata/homebrew-tap/releases/download/v#{version}/convoy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "convoy"
  desc "Convoy — Endeavor Labs internal PSA CLI"
  homepage "https://github.com/endeavordata/convoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "convoy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/convoy"]
    end
  end

  # No zap stanza required

end
