# This file was generated by GoReleaser. DO NOT EDIT.
cask "convoy" do
  version "0.11.0"

  on_macos do
    on_intel do
      sha256 "aa245c42cc848844d5b3630d10189dd769edac3b26278a8f0b807c2954f88c9c"
      url "https://github.com/endeavordata/homebrew-tap/releases/download/v#{version}/convoy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "563bc1335c8d2fe2b2baa38eb077c540d8a346b43f67a5738143808c5b4392b8"
      url "https://github.com/endeavordata/homebrew-tap/releases/download/v#{version}/convoy_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "convoy"
  desc "Convoy — Endeavor Labs internal PSA CLI"
  homepage "https://github.com/endeavordata/convoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "convoy"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/convoy"]
    end
  end

  # No zap stanza required

end
